apiVersion: v1
kind: Service
metadata:
  name: {{ template "virtual-care.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "virtual-care.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: virtual-care
    app.kubernetes.io/part-of: healthcare-platform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # AWS Load Balancer configurations for optimal WebRTC performance
    service.beta.kubernetes.io/aws-load-balancer-type: "{{ .Values.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-type }}"
    service.beta.kubernetes.io/aws-load-balancer-internal: "{{ .Values.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-internal }}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    # Enable WebSocket support for video streaming
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Component=virtual-care,Environment={{ .Release.Namespace }}"
    # Monitoring annotations
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.targetPort }}"
spec:
  type: {{ .Values.service.type }}
  # Enable session affinity for WebRTC connections
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hour timeout for video sessions
  # Preserve client source IP for security
  externalTrafficPolicy: Local
  ports:
    # Main service port for WebRTC and API traffic
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # WebRTC specific ports
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: stun
    - port: 3479
      targetPort: 3479
      protocol: UDP
      name: turn-udp
    - port: 3480
      targetPort: 3480
      protocol: TCP
      name: turn-tcp
    # Metrics port for monitoring
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ template "virtual-care.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}