apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
  annotations:
    # AWS NLB specific annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "{{ .Values.kong.admin.http.containerPort }}"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    # Prometheus metrics scraping
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
    prometheus.io/path: "/metrics"
    # Additional security headers
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"

spec:
  type: {{ .Values.service.type }}
  ports:
    # HTTP proxy port
    - name: proxy-http
      port: {{ .Values.kong.proxy.http.servicePort }}
      targetPort: {{ .Values.kong.proxy.http.containerPort }}
      protocol: TCP
      
    # HTTPS proxy port
    - name: proxy-https
      port: {{ .Values.kong.proxy.tls.servicePort }}
      targetPort: {{ .Values.kong.proxy.tls.containerPort }}
      protocol: TCP
      
    # Admin API port
    - name: admin-api
      port: {{ .Values.kong.admin.http.servicePort }}
      targetPort: {{ .Values.kong.admin.http.containerPort }}
      protocol: TCP
      
    # Metrics port for Prometheus scraping
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP

  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}

  # Session affinity for consistent routing
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours

  # External traffic policy for better security
  externalTrafficPolicy: Local

  # Health check configuration
  healthCheckNodePort: {{ .Values.kong.admin.http.containerPort }}