apiVersion: v1
kind: ConfigMap
metadata:
  name: austa-superapp-config
  namespace: austa
  labels:
    app: austa-superapp
    environment: production
data:
  # API Gateway Configuration
  api-gateway.json: |
    {
      "services": {
        "auth_service_url": "http://auth-service:3000",
        "virtual_care_service_url": "http://virtual-care-service:3000",
        "health_records_service_url": "http://health-records-service:3000",
        "claims_service_url": "http://claims-service:3000",
        "marketplace_service_url": "http://marketplace-service:3000"
      },
      "cors": {
        "allowed_origins": [
          "https://*.austa-health.com",
          "https://admin.austa-health.com",
          "capacitor://localhost",
          "http://localhost:3000"
        ],
        "allowed_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        "max_age": 3600
      },
      "rate_limiting": {
        "requests_per_minute": 1000,
        "requests_per_hour": 50000,
        "burst_multiplier": 1.5,
        "throttling_enabled": true
      }
    }

  # Authentication Service Configuration
  auth-service.json: |
    {
      "session": {
        "name": "austa.sid",
        "max_age": 86400000,
        "same_site": "strict",
        "secure": true,
        "http_only": true
      },
      "security": {
        "max_login_attempts": 5,
        "lockout_duration": 900,
        "password_min_length": 12,
        "password_complexity": {
          "require_uppercase": true,
          "require_lowercase": true,
          "require_numbers": true,
          "require_special": true
        },
        "require_mfa": true,
        "mfa_types": ["authenticator", "sms", "email"],
        "jwt_expiry": 900
      }
    }

  # Virtual Care Service Configuration
  virtual-care.json: |
    {
      "video": {
        "max_participants": 2,
        "quality": {
          "width": {
            "min": 640,
            "ideal": 1280,
            "max": 1920
          },
          "height": {
            "min": 480,
            "ideal": 720,
            "max": 1080
          },
          "frameRate": {
            "min": 15,
            "ideal": 30,
            "max": 60
          },
          "aspectRatio": 1.777778
        },
        "adaptive_quality": true
      },
      "network": {
        "max_bitrate_kbps": 2000,
        "min_bitrate_kbps": 100,
        "max_packet_loss_percentage": 3,
        "reconnection_timeout_ms": 10000,
        "ice_servers": ["stun:stun.austa-health.com:3478"]
      }
    }

  # Health Records Service Configuration
  health-records.json: |
    {
      "storage": {
        "max_file_size_mb": 50,
        "allowed_file_types": ["pdf", "jpg", "png", "dcm"],
        "retention_period_days": 7300,
        "encryption_enabled": true
      },
      "fhir": {
        "version": "R4",
        "validate_resources": true,
        "supported_resources": [
          "Patient",
          "Observation",
          "Condition",
          "Procedure"
        ],
        "terminology_validation": true
      }
    }

  # Global Application Settings
  app-settings.json: |
    {
      "environment": "production",
      "region": "us-east-1",
      "logging": {
        "level": "info",
        "format": "json",
        "enable_request_logging": true
      },
      "monitoring": {
        "enable_metrics": true,
        "metrics_interval": 60,
        "health_check_interval": 30
      }
    }