apiVersion: v1
kind: Secret
metadata:
  name: austa-superapp-secrets
  namespace: austa
  labels:
    app: austa-superapp
    environment: ${ENV}
    compliance: hipaa-lgpd
  annotations:
    rotation.kubernetes.io/schedule: "0 0 1 * *"
    vault.hashicorp.com/agent-inject: "true"
    audit.kubernetes.io/log-level: "RequestResponse"
    backup.velero.io/schedule: "0 2 * * *"
type: Opaque
data:
  # Authentication Secrets
  jwt-secret: ${JWT_SECRET}
  oauth-client-secret: ${OAUTH_CLIENT_SECRET}
  auth0-client-secret: ${AUTH0_CLIENT_SECRET}
  mfa-encryption-key: ${MFA_ENCRYPTION_KEY}
  biometric-secret: ${BIOMETRIC_SECRET}

  # Database Credentials
  postgres-password: ${POSTGRES_PASSWORD}
  mongodb-password: ${MONGODB_PASSWORD}
  redis-password: ${REDIS_PASSWORD}
  backup-encryption-key: ${BACKUP_ENCRYPTION_KEY}

  # Health Records Integration
  fhir-client-secret: ${FHIR_CLIENT_SECRET}
  hl7-api-key: ${HL7_API_KEY}
  dicom-encryption-key: ${DICOM_ENCRYPTION_KEY}
  snomed-license-key: ${SNOMED_LICENSE_KEY}

  # Virtual Care Services
  twilio-auth-token: ${TWILIO_AUTH_TOKEN}
  twilio-api-secret: ${TWILIO_API_SECRET}
  webrtc-secret: ${WEBRTC_SECRET}
  video-encryption-key: ${VIDEO_ENCRYPTION_KEY}

  # Storage Security
  s3-secret-key: ${S3_SECRET_KEY}
  storage-encryption-key: ${STORAGE_ENCRYPTION_KEY}
  phi-encryption-key: ${PHI_ENCRYPTION_KEY}

  # Monitoring & Observability
  grafana-admin-password: ${GRAFANA_ADMIN_PASSWORD}
  apm-secret-token: ${APM_SECRET_TOKEN}
  sentry-auth-token: ${SENTRY_AUTH_TOKEN}
  audit-encryption-key: ${AUDIT_ENCRYPTION_KEY}

  # TLS Certificates
  tls.crt: ${TLS_CERTIFICATE}
  tls.key: ${TLS_PRIVATE_KEY}
  ca.crt: ${CA_BUNDLE}

stringData:
  # Compliance Configuration
  hipaa-compliance: |
    encryption_standard: AES-256-GCM
    key_rotation_period: 30d
    audit_retention: 7y
    phi_protection: enabled

  # Security Policy
  security-policy: |
    min_tls_version: TLS1.3
    encryption_at_rest: true
    network_isolation: strict
    audit_level: full