# AUSTA SuperApp SwiftLint Configuration
# Version: 1.0
# Purpose: Enforce strict code quality and security standards for healthcare application

# Disabled rules that conflict with project style guide
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

# Opt-in rules for enhanced code quality and security
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Included source files
included:
  - src/ios/AUSTASuperApp

# Excluded paths
excluded:
  - src/ios/Pods
  - src/ios/AUSTASuperAppTests
  - src/ios/AUSTASuperAppUITests
  - src/ios/fastlane

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Custom rules for healthcare-specific validations
custom_rules:
  health_data_validation:
    name: "Health Data Validation"
    regex: "(HealthRecord|HealthMetric).*=\\s*nil"
    message: "Health data should be properly validated before assignment"
    severity: warning
  
  secure_storage:
    name: "Secure Storage Usage"
    regex: "UserDefaults\\.standard"
    message: "Use SecureStorage for sensitive data instead of UserDefaults"
    severity: error
  
  phi_data_access:
    name: "PHI Data Access"
    regex: "PHIData.*\\.(read|write)"
    message: "PHI data access must be logged and authorized"
    severity: error
  
  hipaa_compliance:
    name: "HIPAA Compliance"
    regex: "(print|dump).*PHI"
    message: "PHI data must not be logged to console"
    severity: error

# Line length limits
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# File length limits
file_length:
  warning: 400
  error: 500

# Type body length limits
type_body_length:
  warning: 300
  error: 400

# Function body length limits
function_body_length:
  warning: 50
  error: 80

# Cyclomatic complexity limits
cyclomatic_complexity:
  warning: 10
  error: 15

# Type name rules
type_name:
  min_length: 3
  max_length: 50

# Identifier name rules
identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - URL
    - x
    - y

# Nesting limits
nesting:
  type_level:
    warning: 2
    error: 3

# Force usage rules
force_cast: error
force_try: error
force_unwrapping: error