apiVersion: v2
name: virtual-care
version: 1.0.0
description: A Helm chart for AUSTA SuperApp Virtual Care Service providing secure telemedicine capabilities
type: application
appVersion: "1.0.0"

keywords:
  - telemedicine
  - virtual-care
  - healthcare
  - video-consultation

maintainers:
  - name: AUSTA Health
    email: devops@austa.health

# Dependencies required for the virtual care service
dependencies:
  # MongoDB for storing consultation records and medical data
  - name: mongodb
    version: "~12.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  # Redis for session management and real-time features
  - name: redis
    version: "~17.0.0" 
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

# Additional metadata for artifact hub
annotations:
  artifacthub.io/changes: |
    Initial release of virtual care service
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"