# Prometheus Configuration for AUSTA SuperApp Platform
# Version: 2.45.0
# Dependencies: prometheus v2.45.0, alertmanager v0.25.0

# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 1m
  scrape_timeout: 10s
  external_labels:
    environment: production
    region: primary
    compliance_level: hipaa
    platform: austa-superapp

# Rule files containing alert definitions
rule_files:
  - "alerting-rules.yml"

# Scrape configurations for monitoring targets
scrape_configs:
  # Kubernetes pods auto-discovery
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    tls_config:
      insecure_skip_verify: false
      cert_file: /etc/prometheus/certs/client.crt
      key_file: /etc/prometheus/certs/client.key
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: (container_.*|kube_.*|health_.*)

  # API Gateway monitoring
  - job_name: api-gateway
    metrics_path: /metrics
    scheme: https
    basic_auth:
      username: ${PROM_AUTH_USER}
      password: ${PROM_AUTH_PASS}
    static_configs:
      - targets: ['api-gateway:3000']

  # Virtual Care Service monitoring
  - job_name: virtual-care-service
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['virtual-care:8080']

  # Health Records Service monitoring
  - job_name: health-records-service
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['health-records:8081']

  # Claims Service monitoring
  - job_name: claims-service
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['claims:8082']

# Alertmanager configuration
alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets: ['alertmanager:9093']
      timeout: 5s
      api_version: v2

# Storage configuration
storage:
  tsdb:
    retention_time: 15d
    retention_size: 50GB
    wal_compression: true
    min_block_duration: 2h
    max_block_duration: 24h

# Security configuration
security:
  encryption_at_rest: true
  audit_logging: true
  compliance_mode: hipaa